---
title: "Cookbook for Beginners in Ecology: What You Need Before Hands on Anything"
author: "Jiangyue Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: Jiangyue-Wang/URP-hands-on
description: "This is a brief tutorial to undergraduate students major in Ecology, especially in SLS, PKU. Trying to answer: 1)what they must know before hands on experiments or analysis; 2)what are the most commonly used paradigm; 3)where to get help if they want to go into some specific questions. Still under construction."
---

# Prerequisites: English, and only English

Sorry. As you can see, the whole tutorial is mainly written in English instead of the language that most readers are using, Chinese. This is not because I want to practice my English writing(well, to some extent, maybe yes) or trying to make a high-level thing. It's simply because **English is requisite** for you to enter academia, no matter what you are aiming for, to get a future MacArthur's Award or just want to finish some assignments as soon as possible. Most high impact literatures are in English, and the best learning materials you can get online for free are also in English. The latter one is pretty disappointment, but thanks to some generous experts like Xinhai Li(李欣海，公众号：[生物统计学经验分享](https://mp.weixin.qq.com/s/pkSLAJgExkHTDlVlvaV-Qw)) who are dedicated to give excellent, applicable lectures on ecological statistics, things are getting better and better now.

I will try my best to use plain and understandable English to describe and explain. Thus, if you are quite skilled in some topics, you may find the tutorial a bit wordy. But I hope there would be barely any difficulties reading through these chapters, with a basic knowledge of high-school-level mathematics. When encountering some key concepts, especially in [Statistics part](02-basics.Rmd), I 'll also rewrite paragraphs in Chinese to help you better understand and link them to what you've learnt in corresponding lectures.

Again, English is the must but only requisite for you to go into this tutorial. Don't be afraid and let's start.
